### PR TITLE
Provide better error message when a minor branch has no release found

### LINKED ISSUE #156: Bug: "Minor branch must have release" assert firing
[This assert](https://github.com/sociomantic-tsunami/neptune/blob/master/src/release/mergeHelper.d#L382) fires when I try to make a release of a sociomantic internal repo (ask me and I'll show you which one).

Console output:
```
We are on branch v1.2.x
Detected release v1.2.1
core.exception.AssertError@./src/release/mergeHelper.d(383): Assertion failure
----------------
??:? _d_assertp [0x99a81d]
./src/release/mergeHelper.d:383 semver.Version.Version release.mergeHelper.PatchMerger.findNewPatchRelease(release.versionHelper.SemVerBranch) [0x93000b]
./src/release/mergeHelper.d:242 void release.mergeHelper.PatchMerger.tagAndMerge(release.versionHelper.SemVerBranch, release.releaseHelper.ReleaseAction) [0x92fa00]
./src/release/mergeHelper.d:198 release.actions.ActionList release.mergeHelper.PatchMerger.release(release.versionHelper.SemVerBranch) [0x92f89c]
/home/gavinnorman/devel/neptune/src/release/main.d:574 release.actions.ActionList release.main.preparePatchRelease(ref octod.core.HTTPConnection, ref octod.api.repos.Repository, semver.Version.Version[], semver.Version.Version, immutable(char)[]) [0x7cf363]
/home/gavinnorman/devel/neptune/src/release/main.d:116 _Dmain [0x7cdcdf]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x9a0f0b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x9a0e3b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x9a0eb4]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x9a0e3b]
??:? _d_run_main [0x9a0dab]
??:? main [0x7daa81]
??:? __libc_start_main [0x55c5c82f]
```
I deliberately cleared all non-semver branches, but this didn't help.

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**
fixes #156

### CODE REVIEW

File: src/release/mergeHelper.d [hunk 1]
```diff
@@ -380,7 +388,8 @@ class PatchMerger
 
 
         // A minor branch MUST have a release
-        assert(!latest_patch.empty);
+        if (latest_patch.empty)
+            throw new Exception("No release found for minor branch");
```
Comment (mihails-strasuns-sociomantic) [inline src/release/mergeHelper.d]: `enforce(!latest_patch.empty, "No release found for minor branch")` :)

File: src/release/mergeHelper.d [hunk 2]
```diff
@@ -195,7 +195,15 @@ class PatchMerger
 
             foreach (pending; local_pending_branches)
             {
-                this.tagAndMerge(pending.branch, pending.merged);
+                try this.tagAndMerge(pending.branch, pending.merged);
+                catch (Exception exc)
+                {
+                    import std.stdio;
+                    import colorize;
+                    writefln("Failed to handle branch %s: %s".color(fg.red),
```
Comment (mihails-strasuns-sociomantic) [inline src/release/mergeHelper.d]: I think it will be less noisy to just `exc.msg = "When handling branch " ~ pending ~ ":\n" ~ exc.msg` and rethrow.

**Comment by mathias-baumann-sociomantic** [comment]
Updated
