### PR TITLE
Replace pipeShell with pipeProcess and other e-mail fixes

### LINKED ISSUE #111: E-mail fails with error message but release is reported as succesful
I got this when trying to send the e-mail:
```
Would you like to send it to Team <team@example.com> now? y/n: y
/bin/sh: 1: Syntax error: end of file unexpected
All done.
```

I've seen that to send the e-mail a shell is used and the recipient is not quoted at all :scream: !!!

https://github.com/sociomantic-tsunami/neptune/blob/08f073791565825d9ae1d231cd60de5b6cbe8a83/src/release/main.d#L282-L283

I guess it can come from that...

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
Generally speaking, is very bad to execute commands using a shell, as all sort of attacks can be done by injecting further commands using shell tricks.

Unless something is really needed from the shell, a process should be spawn instead, and if a shell is really needed, the command passed should be properly escaped to make sure the shell doesn't do crazy shit.

It is also more wasteful as it will spawn an extra process (the shell) if it's unneeded.

This also adds the To: header to the e-mail and uses less confusing variable names for the e-mail body/payload.

I think it should fix #111, but I couldn't try it yet.

### CODE REVIEW

File: src/release/main.d [hunk 1]
```diff
@@ -183,21 +183,21 @@ void main ( string[] params )
...
             .filter!(a=>a !is null)
             .array);
 
-    writefln("This is the announcement email:\n-----\n%s\n-----", email_body);
-
-    auto recp = getConfig("neptune.mail-recipient").ifThrown("");
+    writefln("This is the announcement email:\n-----\n%s\n-----", email);
 
-    if (recp.length == 0)
+    if (recipient.length == 0)
```
Comment (mihails-strasuns-sociomantic) [inline src/release/main.d]: Order of actions is weird. First you get recipient, then craft mail and only after that check if recipient  is non-zero.

Also turning exception into empty string to immediately check for empty string after is just exception anti-pattern. But that part was already present before.

**Comment by leandro-lucarella-sociomantic** [comment]
Updated (only fixed the non pre-existing issue).

**Comment by leandro-lucarella-sociomantic** [comment]
Rebased.

**Comment by leandro-lucarella-sociomantic** [comment]
This is quite more complicated than I initially thought. There are many many more cases of commands being run (`cmd()`) and some use shell globbing (`*.md`) which can't be immediately be converted to plain `exec`. I will see if there is a glob function in D and otherwise C's can be used, but I need to do a lot more adapting here.

**Comment by mihails-strasuns-sociomantic** [comment]
I don't know of built-in glob but it can be implemented in few lines by combining https://dlang.org/phobos/std_path.html#globMatch with https://dlang.org/phobos/std_file.html#dirEntries

**Comment by leandro-lucarella-sociomantic** [comment]
`dirEntries()` supports passing a glob pattern :sunglasses:

**Comment by mihails-strasuns-sociomantic** [comment]
Ha! No idea how I have missed that :)

**Comment by leandro-lucarella-sociomantic** [comment]
Rebased and massively updated to remove all shell commands.

File: integrationtest/initial_release/shellHelper.d [hunk 2]
```diff
@@ -18,25 +18,45 @@ module integrationtest.initial_release.shellHelper;
...
+        wd = directory to run the command in
+        command = command to run (including arguments). Arguments will be split
+                  based on spaces
+
+    Returns:
+        output of the command
+
+*******************************************************************************/
+
+string cmd ( string wd, string command )
```
Comment (mihails-strasuns-sociomantic) [inline integrationtest/initial_release/shellHelper.d]: This isn't really the same as executing in shell (as it may split args differently than `split` call). Intentional?

File: src/release/main.d [hunk 3]
```diff
@@ -679,9 +684,14 @@ ActionList clearReleaseNotes ( )
 {
     ActionList list;
 
-    list.actions ~= new LocalAction("git rm relnotes/*.md",
+    import std.file: dirEntries, SpanMode;
+    import std.array: array;
+    import std.algorithm.iteration: map;
+    list.actions ~= new LocalAction(["git", "rm"] ~ array(dirEntries("relnotes", "*.md",
+                                     SpanMode.shallow).map!("a.name")),
```
Comment (mihails-strasuns-sociomantic) [inline src/release/main.d]: I'd suggest non-string lambda and some pipeline styling :P 

```D
auto relnotes = dirEntries("relnotes", "*.md", SpanMode.shallow)
       .map!(a => a.name)
       .array();
list.actions ~= new LocalAction(["git", "rm"] ~ relnotes,  "Removing release notes");
```

File: integrationtest/initial_release/shellHelper.d (hunk 2 above)
Comment (leandro-lucarella-sociomantic) [reply integrationtest/initial_release/shellHelper.d]: Nope, it was just for convenience for the tests or for commands that don't have user input, but splitting arguments doesn't trigger expansions (as a shell will do, like `*.md` or `$HOME`) and won't accept shell operators (like `|` or `;`, etc.). All these are the source to errors / security holes.

Comment (leandro-lucarella-sociomantic) [reply integrationtest/initial_release/shellHelper.d]: Oh, I read your question wrongly. Yes, it is intended :)

It is documented that it just does a dump split.

File: src/release/main.d (hunk 3 above)
Comment (leandro-lucarella-sociomantic) [reply src/release/main.d]: I tried the chaining at first but it didn't work, it said something like "MapResultWhatever doesn't have a method array". I could change the `map`, but what would be the advantage?

**Comment by mathias-baumann-sociomantic** [comment]
Please rebase

**Comment by leandro-lucarella-sociomantic** [comment]
There is a failure in the test suite now that I can't understand (at least locally, let's see what Travis says). Maybe you can have a look at it.

**Comment by leandro-lucarella-sociomantic** [comment]
ping @mathias-baumann-sociomantic

**Comment by mathias-baumann-sociomantic** [comment]
It fails because the test can't properly prepare the first commit:

```
Ran: ["git", "commit", "-m", "\"Add", "rel", "notes\""], wd: /home/marenz/sociomantic/neptune/build/devel/tmp/d8cf51b02aa56865/github.com:tester/sandbox code: 1. output: error: pathspec 'rel' did not match any file(s) known to git.
```

**Comment by mathias-baumann-sociomantic** [comment]
For example from this call:

https://github.com/leandro-lucarella-sociomantic/neptune/blob/email/integrationtest/prerelease/main.d#L45

**Comment by leandro-lucarella-sociomantic** [comment]
But do you have any idea why? As far as I can tell this PR has nothing to do with pre-releases, why is it making a prerelease integration test fail?

**Comment by leandro-lucarella-sociomantic** [comment]
Arggh, never mind, is the spaces. I forgot I left that alias...

**Comment by leandro-lucarella-sociomantic** [comment]
Updated, but I still get errors when testing locally and I don't know how to read the logs, I don't know how to track where the error really was :(

**Comment by mathias-baumann-sociomantic** [comment]
To track down this problem I printed the return status & cmd output here: https://github.com/leandro-lucarella-sociomantic/neptune/blob/6a6320f4c1cc60535e203b3ec95b1b02dd75f35c/integrationtest/common/shellHelper.d#L91

**Comment by leandro-lucarella-sociomantic** [comment]
Thanks! With that tip I could track down the problems... I will update the PR soon!

**Comment by leandro-lucarella-sociomantic** [comment]
Updated!

**Comment by leandro-lucarella-sociomantic** [comment]
:tada:
